<template>
  <view class="history-page">
    <!-- 页面标题 -->
    <view class="page-header">
      <text class="h2-title">病史小结</text>
      <text class="sub-title">生成您的就医报告</text>
    </view>

    <!-- 进度指示 -->
    <view class="progress-section" v-if="!showReport">
      <view
        v-for="(question, index) in visibleQuestions"
        :key="question.id"
        class="progress-dot"
        :class="{ active: index <= currentIndex, answered: answers[question.id] }"
      ></view>
    </view>

    <!-- 当前问题 -->
    <view class="question-card card" v-if="currentQuestion && !showReport">
      <view class="question-header">
        <text class="question-number">问题 {{ currentIndex + 1 }}/{{ totalQuestions }}</text>
        <text class="question-type">{{ getQuestionTypeLabel(currentQuestion.type) }}</text>
      </view>
      <text class="question-text">{{ currentQuestion.question }}</text>

      <!-- 文本输入 -->
      <view v-if="currentQuestion.type === 'text'" class="answer-area">
        <input
          v-model="currentAnswer"
          type="text"
          :placeholder="'请输入' + currentQuestion.question"
          class="input answer-input"
          @confirm="nextQuestion"
        />
      </view>

      <!-- 数字输入 -->
      <view v-else-if="currentQuestion.type === 'number'" class="answer-area">
        <input
          v-model="currentAnswer"
          type="number"
          :placeholder="'请输入数字'"
          class="input answer-input"
          @confirm="nextQuestion"
        />
      </view>

      <!-- 多选输入 -->
      <view v-else-if="currentQuestion.type === 'select'" class="answer-area">
        <view class="option-grid">
          <view
            v-for="option in currentQuestion.options"
            :key="option"
            class="option-btn"
            :class="{ active: currentAnswer === option }"
            @click="selectOption(option)"
          >
            {{ option }}
          </view>
        </view>
      </view>

      <!-- 多行文本 -->
      <view v-else-if="currentQuestion.type === 'textarea'" class="answer-area">
        <textarea
          v-model="currentAnswer"
          :placeholder="'请详细描述'"
          class="input answer-textarea"
        />
      </view>

      <!-- 操作按钮 -->
      <view class="question-actions">
        <button v-if="currentIndex > 0" class="btn btn-outline" @click="prevQuestion">
          上一步
        </button>
        <button class="btn btn-primary" @click="nextQuestion">
          {{ currentIndex === totalQuestions - 1 ? '生成报告' : '下一步' }}
        </button>
      </view>
    </view>

    <!-- 预览报告 -->
    <view v-if="showReport" class="report-card card">
      <view class="report-header">
        <text class="report-title">病史报告</text>
        <text class="report-time">{{ formatDate(new Date().toISOString()) }}</text>
      </view>
      <view class="report-content">
        <text class="report-text">{{ medicalReport }}</text>
      </view>
      <view class="report-actions">
        <button class="btn btn-outline share-btn" @click="generateReportImage">
          <text class="btn-icon">📤</text>
          <text class="btn-label">分享报告</text>
        </button>
        <button class="btn btn-primary edit-btn" @click="editReport">
          <text class="btn-icon">✏️</text>
          <text class="btn-label">继续编辑</text>
        </button>
      </view>
    </view>

    <!-- 用于生成图片的报告容器（隐藏） -->
    <view id="report-image-container" class="report-image-container-offscreen" v-if="showReport">
      <view class="report-image-content">
        <view class="report-image-header">
          <text class="report-image-title">病史报告</text>
          <text class="report-image-date">{{ formatDate(new Date().toISOString()) }}</text>
        </view>
        <view class="report-image-body">
          <text class="report-image-text">{{ medicalReport }}</text>
        </view>
        <view class="report-image-footer">
          <text class="report-image-footer-text">Generated by AI 用药助手</text>
        </view>
      </view>
    </view>

    <!-- App 端隐藏 Canvas -->
    <!-- #ifndef H5 -->
    <canvas
      id="report-canvas"
      type="2d"
      style="width: 375px; height: 600px; position: fixed; left: -10000px;"
    />
    <!-- #endif -->

    <!-- 图片预览弹窗 -->
    <ReportImagePreview
      v-model:visible="previewVisible"
      :image-path="reportImagePath"
      @save="saveReportImage"
      @share="shareReportImage"
    />

    <!-- 底部导航 -->
    <view class="bottom-nav" :class="{ hidden: showReport }">
      <button class="btn btn-large btn-outline" @click="goBack">
        返回
      </button>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useHealthStore, medicalHistoryQuestions } from '@/store/health'
import { speakText } from '@/services/voice'
import ReportImagePreview from '@/components/ReportImagePreview.vue'

// #ifdef H5
import html2canvas from 'html2canvas'
// #endif

// #ifndef H5
import { drawReportCanvas } from '@/utils/report-canvas'
// #endif

const healthStore = useHealthStore()

const currentIndex = ref(0)
const currentAnswer = ref('')
const answers = ref<Record<string, string>>({})
const showReport = ref(false)
const medicalReport = ref('')
const showImagePreview = ref(false)
const previewVisible = ref(false) // 用于组件的 v-model

// #ifdef H5
const reportImageUrl = ref('')
// #endif

// #ifndef H5
const reportImagePath = ref('')
// #endif

const visibleQuestions = computed(() => medicalHistoryQuestions)
const totalQuestions = computed(() => visibleQuestions.value.length)
const currentQuestion = computed(() => visibleQuestions.value[currentIndex.value])

// 获取问题类型标签
function getQuestionTypeLabel(type: string): string {
  const labels: Record<string, string> = {
    text: '文本',
    number: '数字',
    select: '选择',
    textarea: '详情'
  }
  return labels[type] || '文本'
}

// 选择选项
function selectOption(option: string) {
  currentAnswer.value = option
}

// 上一步
async function prevQuestion() {
  if (currentIndex.value > 0) {
    await saveCurrentAnswer()
    currentIndex.value--
    currentAnswer.value = answers.value[currentQuestion.value.id] || ''
  }
}

// 下一步
async function nextQuestion() {
  await saveCurrentAnswer()

  if (currentIndex.value < totalQuestions.value - 1) {
    currentIndex.value++
    currentAnswer.value = answers.value[currentQuestion.value.id] || ''
  } else {
    // 生成报告
    await generateReport()
  }
}

// 保存当前答案
async function saveCurrentAnswer() {
  if (currentAnswer.value.trim()) {
    answers.value[currentQuestion.value.id] = currentAnswer.value
    const result = await healthStore.saveMedicalHistoryAnswer(
      currentQuestion.value.id,
      currentAnswer.value
    )
    return result
  }
}

// 生成报告
async function generateReport() {
  // 先保存当前问题的答案
  if (currentAnswer.value.trim()) {
    answers.value[currentQuestion.value.id] = currentAnswer.value
  }

  // 保存所有答案到 store
  const savePromises = []
  for (const [questionId, answer] of Object.entries(answers.value)) {
    if (answer && answer.trim()) {
      savePromises.push(healthStore.saveMedicalHistoryAnswer(questionId, answer))
    }
  }
  await Promise.all(savePromises)

  // 刷新 store 中的答案，确保是最新的
  await healthStore.fetchMedicalHistoryAnswers()

  // 生成报告文本
  medicalReport.value = healthStore.generateMedicalHistoryReport()
  showReport.value = true

  speakText('报告已生成，您可以查看或分享给医生')
}

// 生成报告图片并分享
async function generateReportImage() {
  // #ifdef H5
  try {
    uni.showLoading({ title: '生成图片中...' })

    // 使用 setTimeout 确保 DOM 已更新
    setTimeout(async () => {
      const element = document.getElementById('report-image-container')
      if (!element) {
        uni.showToast({ title: '生成失败', icon: 'none' })
        uni.hideLoading()
        return
      }

      const canvas = await html2canvas(element as HTMLElement, {
        backgroundColor: '#fff',
        scale: 2,
        useCORS: true,
        logging: false
      })

      canvas.toBlob(async (blob) => {
        if (!blob) {
          uni.showToast({ title: '生成失败', icon: 'none' })
          uni.hideLoading()
          return
        }

        // 显示预览
        reportImageUrl.value = URL.createObjectURL(blob)
        showImagePreview.value = true
        previewVisible.value = true
        uni.hideLoading()

        speakText('图片已生成，长按可以保存到相册')
      }, 'image/png')
    }, 100)
  } catch (e) {
    console.error('生成图片失败:', e)
    uni.showToast({ title: '生成失败', icon: 'none' })
    uni.hideLoading()
  }
  // #endif

  // #ifndef H5
  // App 端 - 使用 Canvas 绘制
  try {
    uni.showLoading({ title: '生成图片中...' })

    // 确保 canvas 已就绪
    await new Promise(resolve => setTimeout(resolve, 500))

    const imagePath = await drawReportCanvas(medicalReport.value, 'report-canvas')
    reportImagePath.value = imagePath
    showImagePreview.value = true
    previewVisible.value = true
    uni.hideLoading()

    speakText('图片已生成，长按可以保存到相册')
  } catch (e) {
    console.error('生成图片失败:', e)
    uni.showToast({ title: '生成失败', icon: 'none' })
    uni.hideLoading()
  }
  // #endif
}

// 关闭图片预览弹窗
function closeImageModal() {
  showImagePreview.value = false
  previewVisible.value = false
  // #ifdef H5
  if (reportImageUrl.value) {
    URL.revokeObjectURL(reportImageUrl.value)
    reportImageUrl.value = ''
  }
  // #endif

  // #ifndef H5
  reportImagePath.value = ''
  // #endif
}

// 保存报告图片到相册
async function saveReportImage() {
  // #ifdef H5
  try {
    const response = await fetch(reportImageUrl.value)
    const blob = await response.blob()
    const url = window.URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `病史报告_${new Date().getTime()}.png`
    link.click()
    window.URL.revokeObjectURL(url)
    uni.showToast({ title: '已保存', icon: 'success' })
    closeImageModal()
  } catch (e) {
    uni.showToast({ title: '请长按图片保存', icon: 'none' })
  }
  // #endif

  // #ifndef H5
  uni.saveImageToPhotosAlbum({
    filePath: reportImagePath.value,
    success: () => {
      uni.showToast({ title: '已保存到相册', icon: 'success' })
      closeImageModal()
    },
    fail: (err) => {
      console.error('保存失败:', err)
      uni.showToast({ title: '保存失败', icon: 'none' })
    }
  })
  // #endif
}

// 分享报告图片
async function shareReportImage() {
  // #ifdef H5
  if (navigator.share) {
    try {
      const response = await fetch(reportImageUrl.value)
      const blob = await response.blob()
      const file = new File([blob], 'report.png', { type: 'image/png' })
      await navigator.share({
        title: '病史报告',
        files: [file]
      })
      closeImageModal()
    } catch (e) {
      console.error('分享失败:', e)
      uni.showToast({ title: '请长按图片后分享', icon: 'none' })
    }
  } else {
    uni.showToast({ title: '请长按图片后分享', icon: 'none' })
  }
  // #endif

  // #ifndef H5
  uni.share({
    filePath: reportImagePath.value,
    success: () => {
      uni.showToast({ title: '分享成功', icon: 'success' })
      closeImageModal()
    },
    fail: (err) => {
      console.error('分享失败:', err)
      uni.showToast({ title: '分享失败', icon: 'none' })
    }
  })
  // #endif
}

// 编辑报告
function editReport() {
  showReport.value = false

  // 找到第一个未回答的问题
  let firstUnansweredIndex = 0
  for (let i = 0; i < totalQuestions.value; i++) {
    const question = visibleQuestions.value[i]
    if (!answers.value[question.id]) {
      firstUnansweredIndex = i
      break
    }
  }

  currentIndex.value = firstUnansweredIndex
  currentAnswer.value = answers.value[currentQuestion.value.id] || ''
}

// 返回
function goBack() {
  if (showReport.value) {
    showReport.value = false
  } else {
    uni.navigateBack()
  }
}

// 格式化日期
function formatDate(dateStr: string): string {
  const date = new Date(dateStr)
  return `${date.getFullYear()}年${date.getMonth() + 1}月${date.getDate()}日`
}

onMounted(async () => {
  // 加载已有答案
  await healthStore.fetchMedicalHistoryAnswers()

  const existingAnswers: Record<string, string> = {}
  healthStore.medicalHistoryAnswers.forEach(a => {
    existingAnswers[a.question_id] = a.answer
  })
  answers.value = existingAnswers

  // 检查是否有完整的答案（所有问题都已回答）
  const answeredCount = Object.keys(existingAnswers).length
  const hasName = !!existingAnswers['name']

  console.log('病史问答加载完成:', {
    总题目数: totalQuestions.value,
    已答题数: answeredCount,
    是否填写姓名: hasName
  })

  // 如果已填写姓名（表示已完成过报告），直接显示报告页面
  if (hasName && answeredCount >= 5) {
    // 已有完整答案，直接生成报告
    medicalReport.value = healthStore.generateMedicalHistoryReport()
    showReport.value = true
    currentIndex.value = 0
    currentAnswer.value = ''
  } else {
    // 答案不完整，从第一个问题开始
    currentAnswer.value = existingAnswers[visibleQuestions.value[0]?.id] || ''
  }
})
</script>

<style lang="scss" scoped>
.history-page {
  min-height: 100vh;
  background: #F5F5F5;
  padding-bottom: 40rpx;
}

.page-header {
  background: linear-gradient(135deg, #2196F3, #1976D2);
  padding: 40rpx 32rpx;
}

.h2-title {
  color: white;
  font-size: 36rpx;
}

.sub-title {
  color: rgba(255, 255, 255, 0.8);
  font-size: 26rpx;
  margin-top: 8rpx;
}

.progress-section {
  display: flex;
  justify-content: center;
  gap: 12rpx;
  padding: 32rpx;
}

.progress-dot {
  width: 16rpx;
  height: 16rpx;
  border-radius: 50%;
  background: #E0E0E0;
  transition: all 0.3s;
}

.progress-dot.active {
  background: #2196F3;
}

.progress-dot.answered {
  background: #4CAF50;
}

.card {
  background: white;
  border-radius: 16rpx;
  padding: 28rpx;
  margin: 0 32rpx 24rpx;
  box-shadow: 0 4rpx 12rpx rgba(0, 0, 0, 0.06);
}

.question-header {
  display: flex;
  justify-content: space-between;
  margin-bottom: 20rpx;
}

.question-number {
  font-size: 24rpx;
  color: #2196F3;
  font-weight: 500;
}

.question-type {
  font-size: 24rpx;
  color: #999;
}

.question-text {
  font-size: 32rpx;
  font-weight: 600;
  color: #333;
  line-height: 1.5;
  margin-bottom: 32rpx;
}

.answer-area {
  margin-bottom: 32rpx;
}

.answer-input {
  width: 100%;
  padding: 12rpx 16rpx;
  border: 2rpx solid #E0E0E0;
  border-radius: 12rpx;
  font-size: 28rpx;
  background: white;
  transition: all 0.2s;
}

.answer-input:focus {
  border-color: #2196F3;
  box-shadow: 0 0 0 4rpx #E3F2FD;
  outline: none;
}

.answer-textarea {
  width: 100%;
  height: 160rpx;
  padding: 12rpx 16rpx;
  border: 2rpx solid #E0E0E0;
  border-radius: 12rpx;
  font-size: 28rpx;
  background: white;
  transition: all 0.2s;
}

.answer-textarea:focus {
  border-color: #2196F3;
  box-shadow: 0 0 0 4rpx #E3F2FD;
  outline: none;
}

.option-grid {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: 16rpx;
}

.option-btn {
  padding: 20rpx;
  background: #F5F5F5;
  border-radius: 12rpx;
  text-align: center;
  font-size: 26rpx;
  color: #666;
  transition: all 0.2s;
}

.option-btn.active {
  background: #E3F2FD;
  color: #2196F3;
  font-weight: 600;
  border: 2rpx solid #2196F3;
}

.question-actions {
  display: flex;
  gap: 20rpx;
}

.question-actions .btn {
  flex: 1;
  padding: 16rpx 24rpx;
  min-height: 48rpx;
  font-size: 28rpx;
  border-radius: 12rpx;
}

/* 覆盖全局按钮样式 */
.btn {
  padding: 16rpx 24rpx;
  min-height: 48rpx;
  font-size: 28rpx;
  border-radius: 12rpx;
}

.btn-outline {
  background-color: transparent;
  border: 2rpx solid #2196F3;
  color: #2196F3;
  padding: 16rpx 24rpx;
  min-height: 48rpx;
}

.btn-outline:active {
  background-color: #E3F2FD;
}

.btn-primary {
  background: linear-gradient(135deg, #2196F3, #1976D2);
  color: white;
  border: none;
  padding: 16rpx 24rpx;
  min-height: 48rpx;
}

.report-card {
  margin-top: 40rpx;
  margin-bottom: 40rpx;
  padding-bottom: 32rpx;
}

.report-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 20rpx;
}

.report-title {
  font-size: 32rpx;
  font-weight: bold;
  color: #333;
}

.report-time {
  font-size: 24rpx;
  color: #999;
}

.report-content {
  background: #F5F5F5;
  border-radius: 12rpx;
  padding: 24rpx;
  margin-bottom: 24rpx;
  max-height: 600rpx;
  overflow-y: auto;
}

.report-text {
  font-size: 26rpx;
  color: #333;
  line-height: 1.8;
  white-space: pre-wrap;
}

.report-actions {
  display: flex;
  gap: 20rpx;
  margin-bottom: 40rpx;
}

.report-actions .btn {
  flex: 1;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8rpx;
  white-space: nowrap;
  padding: 14rpx 20rpx;
  min-height: 44rpx;
  font-size: 26rpx;
  border-radius: 12rpx;
}

.report-actions .btn-icon {
  flex-shrink: 0;
  font-size: 28rpx;
  line-height: 1;
}

.report-actions .btn-label {
  flex-shrink: 0;
  font-size: 24rpx;
  white-space: nowrap;
}

.bottom-nav {
  position: fixed;
  bottom: 0;
  left: 0;
  right: 0;
  padding: 20rpx 32rpx;
  padding-bottom: calc(20rpx + env(safe-area-inset-bottom));
  background: white;
  box-shadow: 0 -4rpx 16rpx rgba(0, 0, 0, 0.08);
  z-index: 100;
}

.bottom-nav .btn {
  padding: 14rpx 24rpx;
  min-height: 44rpx;
  font-size: 26rpx;
  border-radius: 12rpx;
}

.bottom-nav.hidden {
  display: none;
}

/* 隐藏的报告图片容器 - 用于生成图片（移到屏幕外） */
.report-image-container-offscreen {
  position: absolute;
  left: -10000px;
  top: 0;
  width: 375px;
}

.report-image-content {
  background: linear-gradient(180deg, #fff 0%, #f8f9fa 100%);
  border-radius: 16px;
  overflow: hidden;
}

.report-image-header {
  background: linear-gradient(135deg, #2196F3, #1976D2);
  padding: 30px 24px;
  text-align: center;
}

.report-image-title {
  display: block;
  font-size: 24px;
  font-weight: 700;
  color: white;
  margin-bottom: 8px;
}

.report-image-date {
  display: block;
  font-size: 14px;
  color: rgba(255, 255, 255, 0.8);
}

.report-image-body {
  padding: 24px;
  background: white;
  min-height: 400px;
}

.report-image-text {
  display: block;
  font-size: 14px;
  line-height: 1.8;
  color: #333;
  white-space: pre-wrap;
  font-family: -apple-system, BlinkMacSystemFont, 'PingFang SC', 'Helvetica Neue', Helvetica, Arial, sans-serif;
}

.report-image-footer {
  background: #f8f9fa;
  padding: 16px 24px;
  text-align: center;
  border-top: 1px solid #e0e0e0;
}

.report-image-footer-text {
  display: block;
  font-size: 12px;
  color: #999;
}

/* 图片预览弹窗 */
.image-overlay {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: rgba(0, 0, 0, 0.6);
  z-index: 999;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 32rpx;
}

.image-modal {
  background: white;
  border-radius: 24rpx;
  width: 100%;
  max-width: 400rpx;
  overflow: hidden;
  animation: fadeIn 0.3s ease;
}

.image-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 24rpx 28rpx;
  border-bottom: 1rpx solid #f0f0f0;
}

.image-title {
  font-size: 30rpx;
  font-weight: 600;
  color: #333;
}

.image-close {
  font-size: 40rpx;
  color: #999;
  width: 48rpx;
  height: 48rpx;
  display: flex;
  align-items: center;
  justify-content: center;
}

.image-content {
  padding: 32rpx;
  display: flex;
  align-items: center;
  justify-content: center;
  min-height: 400rpx;
  background: #f8f9fa;
}

.report-image {
  width: 100%;
  height: auto;
  border-radius: 12rpx;
}

.image-loading {
  font-size: 28rpx;
  color: #999;
}

.image-footer {
  padding: 24rpx 28rpx;
  padding-bottom: calc(24rpx + env(safe-area-inset-bottom));
}

.image-footer .btn {
  width: 100%;
  height: 48rpx;
  font-size: 28rpx;
  padding: 14rpx 24rpx;
}

@keyframes fadeIn {
  from {
    opacity: 0;
    transform: scale(0.9);
  }
  to {
    opacity: 1;
    transform: scale(1);
  }
}
</style>
