/**
 * Canvas 绘制工具函数 - App 端报告分享图片生成
 * 使用 uni-app Canvas 2D API 原生绘制报告图片
 */

export interface ReportData {
  title: string
  date: string
  sections: Array<{
    title?: string
    content: string
  }>
  footer: string
}

/**
 * 解析报告文本为结构化数据
 */
export function parseReportText(reportText: string): ReportData {
  const lines = reportText.split('\n')
  const sections: Array<{ title?: string; content: string }> = []
  let currentSection: { title?: string; content: string[] } = { content: [] }

  for (const line of lines) {
    const trimmed = line.trim()
    if (!trimmed) continue

    // 检测 section 标题 === 标题 ===
    if (trimmed.startsWith('===') && trimmed.endsWith('===')) {
      if (currentSection.content.length > 0) {
        sections.push({ title: currentSection.title, content: currentSection.content.join('\n') })
      }
      currentSection = {
        title: trimmed.replace(/===/g, '').trim(),
        content: []
      }
    } else if (trimmed.includes(':')) {
      // 键值对行
      currentSection.content.push(trimmed)
    } else {
      currentSection.content.push(trimmed)
    }
  }

  if (currentSection.content.length > 0) {
    sections.push({ title: currentSection.title, content: currentSection.content.join('\n') })
  }

  return {
    title: '病史报告',
    date: new Date().toLocaleDateString('zh-CN'),
    sections,
    footer: 'Generated by AI 用药助手'
  }
}

/**
 * 文本自动换行（传统 Canvas API 版本）
 * 由于 uni.createCanvasContext 不支持 measureText，使用固定字符数换行
 * 根据 maxWidth 动态计算每行字符数
 */
function wrapText(ctx: any, text: string, maxWidth: number): string[] {
  // 根据可用宽度计算每行字符数
  // Canvas 375px 宽，padding 40px，可用宽度约 295px
  // 中文字符约 14-16px 宽，英文字符约 8-10px 宽
  // 保守估计每行 20 个字符（混合场景）
  const charsPerLine = 20
  const lines: string[] = []
  const paragraphs = text.split('\n')

  for (const paragraph of paragraphs) {
    if (!paragraph) continue
    if (paragraph.length <= charsPerLine) {
      lines.push(paragraph)
    } else {
      for (let i = 0; i < paragraph.length; i += charsPerLine) {
        lines.push(paragraph.slice(i, i + charsPerLine))
      }
    }
  }
  return lines
}

/**
 * 在 Canvas 上绘制报告图片（使用传统 Canvas API）
 * @param reportText 报告文本
 * @returns 临时图片文件路径
 */
export async function drawReportCanvas(
  reportText: string
): Promise<string> {
  return new Promise((resolve, reject) => {
    // 使用 uni.createCanvasContext 创建 Canvas 上下文
    const ctx = uni.createCanvasContext('report-canvas')

    // 画布尺寸（与样式一致）
    const width = 375
    const height = 800
    const padding = 40 // 增加边距

    // 解析报告
    const data = parseReportText(reportText)

    // 0. 先绘制白色背景
    ctx.setFillStyle('#FFFFFF')
    ctx.fillRect(0, 0, width, height)

    // 1. 绘制顶部背景
    ctx.setFillStyle('#2196F3')
    ctx.fillRect(0, 0, width, 120)

    // 2. 绘制标题 - 居中显示
    ctx.setFillStyle('#FFFFFF')
    ctx.setFontSize(24)
    ctx.setTextAlign('center')
    ctx.fillText(data.title, width / 2, 40)

    // 3. 绘制日期 - 右对齐
    ctx.setFillStyle('rgba(255,255,255,0.8)')
    ctx.setFontSize(14)
    ctx.setTextAlign('right')
    ctx.fillText(data.date, width - padding, 40)

    // 4. 绘制报告正文
    let y = 160
    const lineHeight = 28

    for (const section of data.sections) {
      // 绘制 section 标题
      if (section.title) {
        ctx.setFillStyle('#2196F3')
        ctx.setFontSize(16)
        ctx.setTextAlign('left')
        ctx.fillText(`【${section.title}】`, padding, y)
        y += lineHeight + 10
      }

      // 绘制正文内容 - 每行都明确设置对齐方式
      const lines = wrapText(ctx, section.content, width - padding * 2)
      for (const line of lines) {
        ctx.setTextAlign('left')
        ctx.setFillStyle('#333333')
        ctx.setFontSize(14)
        ctx.fillText(line, padding, y)
        y += lineHeight
      }
      y += 14 // section 间距
    }

    // 5. 绘制底部
    ctx.setFillStyle('#F8F9FA')
    ctx.fillRect(0, height - 50, width, 50)
    ctx.setFillStyle('#999999')
    ctx.setFontSize(12)
    ctx.setTextAlign('center')
    ctx.fillText(data.footer, width / 2, height - 25)

    // 6. 导出图片
    ctx.draw(false, () => {
      // 延迟导出以确保绘制完成
      setTimeout(() => {
        uni.canvasToTempFilePath({
          canvasId: 'report-canvas',
          success: (res) => {
            console.log('canvasToTempFilePath success:', res.tempFilePath)
            resolve(res.tempFilePath)
          },
          fail: (err) => {
            console.error('canvasToTempFilePath 失败:', err)
            reject(err)
          }
        })
      }, 300)
    })
  })
}

/**
 * 导出 Canvas 为临时图片文件
 */
export async function exportCanvasToImage(canvas: any): Promise<string> {
  return new Promise((resolve, reject) => {
    uni.canvasToTempFilePath({
      canvas,
      success: (res) => resolve(res.tempFilePath),
      fail: reject
    })
  })
}
